ingress:
  # early testing
  hostname: novostoic.frontend.mmli2.ncsa.illinois.edu
  
  # MIGRATION: eventually enable prod redirect
  #hostname: novostoic.platform.moleculemaker.org
  #extraHosts:
  #- novostoic.frontend.mmli2.ncsa.illinois.edu
  tls: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.tls: "true"
    # MIGRATION: eventually enable prod redirect
    #traefik.ingress.kubernetes.io/router.middlewares: "alphasynthesis-novostoic-prod-domain-redirect@kubernetescrd"

controller:
  image: moleculemaker/novostoic-frontend:main

config:
  hostname: "https://mmli.fastapi.mmli2.ncsa.illinois.edu"
  basePath: ""
  signInUrl: "https://auth.platform.moleculemaker.org/oauth2/start?rd=https%3A%2F%2Fchemcraper.platform.moleculemaker.org%2Fconfiguration"
  signOutUrl: "https://auth.platform.moleculemaker.org/oauth2/sign_out?rd=https%3A%2F%2Fnovostoic.platform.moleculemaker.org%2Fconfiguration"
  userInfoUrl: "https://auth.platform.moleculemaker.org/oauth2/userinfo"

extraDeploy:
- apiVersion: traefik.io/v1alpha1
  kind: Middleware
  metadata:
    name: novostoic-prod-domain-redirect
    namespace: alphasynthesis
  spec:
    redirectRegex:
      regex: "^https://novostoic.frontend.mmli2.ncsa.illinois.edu/(.*)"
      replacement: "https://novostoic.platform.moleculemaker.org/${1}"
      permanent: true
